# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  rust:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    parameters:
      toolchain:
        type: string
      features:
        type: string
    environment:
      CARGO_INCREMENTAL: 0
      CARGO_NET_RETRY: 10
      RUSTUP_MAX_RETRIES: 10
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTFLAGS: "-D warnings"
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_PROFILE_BENCH_DEBUG: 0
      CI: 1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install rust
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y --profile minimal --default-toolchain << parameters.toolchain >>
      - run: source "$HOME/.cargo/env"
      - run:
          name: cargo test
          command: cargo -v test << parameters.features >> -- --nocapture
      - run:
          name: cargo test no_std
          command: cargo -v test --no-default-features -- --nocapture

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  rust-workflow:
    jobs:
      - rust:
          name: Rust AArch64 (stable)
          toolchain: stable
          features: --all-features
      - rust:
          name: Rust AArch64 (1.61.0)
          toolchain: 1.61.0
          features: --all-features
      - rust:
          name: Rust AArch64 (nightly)
          toolchain: nightly
          features: --all-features
